[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "npx prisma db push && echo 'PRISMA_DONE' && node src/index.js 2>&1"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
